# Generated by Django 5.0.7 on 2024-08-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('reportType', models.CharField(choices=[('SH', '간접 흡연 구역'), ('SM', '흡연 구역')], max_length=2)),
                ('secondhandSmokingPlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.secondhandsmokingplace')),
                ('smokingPlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.smokingplace')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
