# Generated by Django 5.0.7 on 2024-07-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('imageUrl', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NoSmokingPlace',
            fields=[
                ('place', models.OneToOneField(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='place.place')),
            ],
        ),
        migrations.CreateModel(
            name='SecondhandSmokingPlace',
            fields=[
                ('place', models.OneToOneField(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='place.place')),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SmokingPlace',
            fields=[
                ('place', models.OneToOneField(db_column='placeId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='place.place')),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('ashtray', models.BooleanField()),
                ('isIndoor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikesId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('NoSmokingPlaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.nosmokingplace', verbose_name='NoSmokingPlace')),
            ],
        ),
    ]
