# Generated by Django 5.0.7 on 2024-07-30 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='NoSmokingPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='place.place')),
                ('NoSmokingPlaceId', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='SecondhandSmokingPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='place.place')),
                ('SecondhandSmokingPlaceId', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='SmokingPlace',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='place.place')),
                ('SmokingPlaceId', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('ashtray', models.BooleanField()),
                ('isIndoor', models.BooleanField()),
            ],
            bases=('place.place',),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('LikesId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('NoSmokingPlaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.nosmokingplace', verbose_name='NoSmokingPlace')),
            ],
        ),
    ]
